backend:
  name: git-gateway
  branch: master

# DEVELOPMENT MODE
# access to /admin; run in terminal: npx netlify-cms-proxy-server
# backend:
#   name: proxy
#   proxy_url: http://localhost:8081/api/v1
#   branch: master

# MEDIA
media_folder: static/img
public_folder: /img

# COLLECTIONS
collections:
  # PRODUCTS ENGLISH
  - name: productsEN
    label: English Products
    label_singular: Product
    slug: "{{fields.title}}"
    editor:
      preview: false
    create: true
    folder: src/dictionary/products/en
    identifier_field: title
    fields:
      - name: templateKey
        label: Template Key
        widget: hidden
        default: post
      - name: language
        label: Language
        widget: hidden
        default: en
      - name: sku
        label: SKU
        widget: string
      - name: stock
        label: Stock
        widget: number
        value_type: int
        min: 0
      - name: title
        label: Title
        widget: string
      - name: color
        label: Color
        hint: Brand color of product in HSL or HEX format
        widget: string
      - name: sort
        label: Sort
        widget: number
        value_type: int
        min: 0
      - name: cover
        label: Cover
        widget: object
        fields:
          - name: image
            label: Image
            widget: image
          - name: title
            label: Title
            widget: string
          - name: text
            label: Text
            widget: string
      - name: introduction
        label: Introduction
        widget: object
        fields:
          - name: introline
            label: Introline
            widget: string
            required: false
            default: ""
          - name: label
            label: Label
            widget: string
            required: false
            default: ""
          - name: title
            label: Title
            widget: string
          - name: subtitle
            label: Subtitle
            widget: string
          - name: text
            label: Text
            widget: string
          - name: video
            label: Video
            widget: file
            required: false
            default: ""
          - name: image
            label: Image
            widget: image
      - name: features
        label: About
        widget: object
        fields:
          - name: title
            label: Title
            widget: string
          - name: subtitle
            label: Subtitle
            widget: string
            required: false
            default: ""
          - name: text
            label: Text
            widget: string
          - name: image
            label: Image
            widget: image
          - name: video
            label: Video
            widget: file
            required: false
            default: ""
      - name: slider
        label: Slider
        widget: list
        min: 1
        fields:
          - name: type
            label: Type
            widget: hidden
            default: slide
          - name: title
            label: Title
            widget: string
          - name: text
            label: Text
            widget: string
      - name: highlights
        label: Gallery
        widget: list
        min: 1
        fields:
          - name: type
            label: Type
            widget: inline-select
            options:
              - image
              - video
          - name: image
            label: Image
            widget: image
          - name: video
            label: Video
            widget: file
            required: false
            default: ""
      - name: store
        label: Bundle images
        widget: object
        fields:
          - name: title
            label: Title
            widget: string
          - name: text
            label: Text
            widget: string
            required: false
            default: ""
          - name: items
            label: Items
            widget: list
            min: 1
            fields:
              - name: title
                label: Title
                widget: string
              - name: subtitle
                label: Subtitle
                widget: string
                required: false
                default: ""
              - name: description
                label: Description
                widget: string
                required: false
                default: ""
              - name: image
                label: Image
                widget: image
      - name: description
        label: Description
        widget: object
        fields:
          - name: title
            label: Title
            widget: string
          - name: subtitle
            label: Subtitle
            widget: string
            required: false
            default: ""
          - name: text
            label: Text
            widget: string
          - name: image
            label: Image
            widget: image

# PRODUCTS ARABIC
  - name: productsAR
    label: Arabic Products
    label_singular: Product
    slug: "{{fields.title}}"
    editor:
      preview: false
    create: true
    folder: src/dictionary/products/ar
    identifier_field: title
    fields:
      - name: templateKey
        label: Template Key
        widget: hidden
        default: post
      - name: language
        label: Language
        widget: hidden
        default: ar
      - name: sku
        label: SKU
        widget: string
      - name: stock
        label: Stock
        widget: number
        value_type: int
        min: 0
      - name: title
        label: Title
        widget: string
      - name: color
        label: Color
        hint: Brand color of product in HSL or HEX format
        widget: string
      - name: sort
        label: Sort
        widget: number
        value_type: int
        min: 0
      - name: cover
        label: Cover
        widget: object
        fields:
          - name: image
            label: Image
            widget: image
          - name: title
            label: Title
            widget: string
          - name: text
            label: Text
            widget: string
      - name: introduction
        label: Introduction
        widget: object
        fields:
          - name: introline
            label: Introline
            widget: string
            required: false
            default: ""
          - name: label
            label: Label
            widget: string
            required: false
            default: ""
          - name: title
            label: Title
            widget: string
          - name: subtitle
            label: Subtitle
            widget: string
          - name: text
            label: Text
            widget: string
          - name: video
            label: Video
            widget: file
            required: false
            default: ""
          - name: image
            label: Image
            widget: image
      - name: features
        label: About
        widget: object
        fields:
          - name: title
            label: Title
            widget: string
          - name: subtitle
            label: Subtitle
            widget: string
            required: false
            default: ""
          - name: text
            label: Text
            widget: string
          - name: image
            label: Image
            widget: image
          - name: video
            label: Video
            widget: file
            required: false
            default: ""
      - name: slider
        label: Slider
        widget: list
        min: 1
        fields:
          - name: type
            label: Type
            widget: hidden
            default: slide
          - name: title
            label: Title
            widget: string
          - name: text
            label: Text
            widget: string
      - name: highlights
        label: Gallery
        widget: list
        min: 1
        fields:
          - name: type
            label: Type
            widget: inline-select
            options:
              - image
              - video
          - name: image
            label: Image
            widget: image
          - name: video
            label: Video
            widget: file
            required: false
            default: ""
      - name: store
        label: Bundle images
        widget: object
        fields:
          - name: title
            label: Title
            widget: string
          - name: text
            label: Text
            widget: string
            required: false
            default: ""
          - name: items
            label: Items
            widget: list
            min: 1
            fields:
              - name: title
                label: Title
                widget: string
              - name: subtitle
                label: Subtitle
                widget: string
                required: false
                default: ""
              - name: description
                label: Description
                widget: string
                required: false
                default: ""
              - name: image
                label: Image
                widget: image
      - name: description
        label: Description
        widget: object
        fields:
          - name: title
            label: Title
            widget: string
          - name: subtitle
            label: Subtitle
            widget: string
            required: false
            default: ""
          - name: text
            label: Text
            widget: string
          - name: image
            label: Image
            widget: image
# SETTINGS EN
  - name: settingsEn
    label: English Settings
    label_singular: setting
    slug: "{{fields.language}}"
    editor:
      preview: false
    create: true
    delete: false
    folder: src/dictionary/settings/en
    identifier_field: language
    fields:
      - name: templateKey
        label: Template Key
        widget: hidden
        default: post
      - name: language
        label: Language
        widget: hidden
        default: en
      - name: buttons
        label: Buttons text
        widget: object
        fields:
          - name: addToCart
            label: Add to cart
            widget: string
          - name: watchVideo
            label: Watch video
            widget: string
          - name: getTheDeal
            label: Get the deal
            widget: string
          - name: checkout
            label: Checkout
            widget: string
          - name: total
            label: Total
            widget: string
          - name: deals
            label: Deals
            widget: string
          - name: watchVideoIcon
            label: watchVideoIcon
            widget: hidden
            default: play
      - name: texts
        label: Texts
        widget: object
        fields:
          - name: sold
            label: Sold
            widget: string
          - name: remaining
            label: Remaining
            widget: string
          - name: soldOut
            label: Sold out
            widget: string
# SETTINGS AR
  - name: settingsAr
    label: Arabic Settings
    label_singular: setting
    slug: "{{fields.language}}"
    editor:
      preview: false
    create: true
    delete: false
    folder: src/dictionary/settings/ar
    identifier_field: language
    fields:
      - name: templateKey
        label: Template Key
        widget: hidden
        default: post
      - name: language
        label: Language
        widget: hidden
        default: ar
      - name: buttons
        label: Buttons text
        widget: object
        fields:
          - name: addToCart
            label: Add to cart
            widget: string
          - name: watchVideo
            label: Watch video
            widget: string
          - name: getTheDeal
            label: Get the deal
            widget: string
          - name: checkout
            label: Checkout
            widget: string
          - name: total
            label: Total
            widget: string
          - name: deals
            label: Deals
            widget: string
          - name: watchVideoIcon
            label: watchVideoIcon
            widget: hidden
            default: play
      - name: texts
        label: Texts
        widget: object
        fields:
          - name: sold
            label: Sold
            widget: string
          - name: remaining
            label: Remaining
            widget: string
          - name: soldOut
            label: Sold out
            widget: string